# Generated by Django 2.2.4 on 2019-08-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('street', models.CharField(max_length=125)),
                ('postcode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=125)),
            ],
        ),
    ]
